apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume.fullname" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "resume.name" . }}
    helm.sh/chart: {{ include "resume.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
      protocol: TCP
      name: mysql-port
  selector:
    app.kubernetes.io/name: {{ include "resume.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
