apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  namespace: resume
  name: "resume"
  labels:
    app: resume
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: resume
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "disk-python-project"
