apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-pvc
  namespace: resume
  labels:
    app: resume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: resume
